name: Push pages

# TODO WOrkflow call / tag push...?>
on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
        GH_PAGES_BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v5
        with:
            path: repo

      - uses: actions/checkout@v5
        with:
            ref: ${{ env.GH_PAGES_BRANCH}}
            path: ${{ env.GH_PAGES_BRANCH}}

        # https://github.com/mattnotmitt/doxygen-action/releases/tag/1.12.0
      - name: Generate Doxygen documentation
        # uses: mattnotmitt/doxygen-action@b84fe17600245bb5db3d6c247cc274ea98c15a3b
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          doxygen repo/Doxyfile

      - name: Post-process docs
        run: |
          mv docs/html ${GH_PAGES_BRANCH}/${{ inputs.VERSION }}

          # doc-index.html
          sed -i '/Development Branch/a\<li><a href="https://github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_REF_NAME}/Reference_Manual.md">${{ inputs.VERSION }}</a></li>' ${GH_PAGES_BRANCH}/doc-index.html

          # api-index.html
          sed -i '/<ul>/a\  <li><a href="${{ inputs.VERSION }}/index.html">${{ inputs.VERSION }}</a></li>' ${GH_PAGES_BRANCH}/api-index.html

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.ref_name }}_doc_update
          title: Add the new C++ client release ${{ github.ref_name }} documentation
          body: ""
          path: ${{ env.GH_PAGES_BRANCH}}
